name: Reusable WF
on:
 workflow_call: 
    inputs:
       name:
        description: "Input1"
        type: string
        required: true
jobs:
    Checkout:
        runs-on: ubuntu-latest
        steps:
         - uses: actions/checkout@v3
         - run: ls -a

    Log-Info:
        runs-on: ubuntu-latest
        steps:
         - run: echo ${{inputs.name}}

   
